export const GET_PRICE_INC = "GET_PRICE_INC";
export const GET_PRICE_EX = "GET_PRICE_EX";
export const GET_PRICE_DISCOUNT = "GET_PRICE_DISCOUNT";
export const TOTAL_PRICE_INC = "TOTAL_PRICE_INC";
export const TOTAL_PRICE_EX = "TOTAL_PRICE_EX";
export const TOTAL_PRICE_DISCOUNT = "TOTAL_PRICE_DISCOUNT";
