export const GET_PRODUCTS = "GET_PRODUCTS";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const SELECTED_PRODUCT_LIST = "SELECTED_PRODUCT_LIST";
export const UPDATE_SELECTED_PRODUCT = "UPDATE_SELECTED_PRODUCT";
export const MUTUATE_SELECTED_PRODUCT = "MUTUATE_SELECTED_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const QUANTITY_PRODUCT = "QUANTITY_PRODUCT";
